# Generated by Django 3.2 on 2022-06-14 08:47

import app_kin_media.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('album_id', models.AutoField(primary_key=True, serialize=False)),
                ('album_genre', models.IntegerField(choices=[(0, 'reggea'), (1, 'hip-hop'), (2, 'pop'), (3, 'soul'), (4, 'RnB')], default=0, verbose_name='Difficulty')),
                ('album_name', models.CharField(default='unknown', max_length=255)),
                ('album_cover', models.ImageField(upload_to=app_kin_media.models.album_cover_directory)),
                ('album_description', models.CharField(default='name', max_length=255)),
                ('album_release_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
                'ordering': ['album_id'],
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.AutoField(primary_key=True, serialize=False)),
                ('artist_name', models.CharField(default='unknown', max_length=255)),
                ('artist_photo', models.ImageField(upload_to=app_kin_media.models.artist_photo_directory_path)),
                ('artist_description', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Artist',
                'verbose_name_plural': 'Artists',
                'ordering': ['artist_id'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('track_id', models.AutoField(primary_key=True, serialize=False)),
                ('track_description', models.CharField(max_length=100)),
                ('track_name', models.CharField(max_length=50)),
                ('track_file', models.FileField(null=True, upload_to='')),
                ('album', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app_kin_media.album')),
                ('artist', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app_kin_media.artist')),
            ],
            options={
                'verbose_name': 'Track',
                'verbose_name_plural': 'Tracks',
                'ordering': ['track_id'],
            },
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app_kin_media.artist'),
        ),
    ]
